### ISSUE TITLE
npm install fails on Node 12.10

### ISSUE THREAD

**Issue by unelsson** [jehervy/node-virtual-gamepads#69]
Error: 
```
binding.cc:222:43: error: no matching function for call to ‘v8::Value::BooleanValue()’
  222 |   bool persistent = info[3]->BooleanValue();
```

**Comment by robsdedude** [comment]
Could you give me some more details?
What os are you using and what npm version?

**Comment by unelsson** [comment]
Linux Manjaro. Current npm is 5.0.0, though I don't know if it was that when I tested this bug. I downgraded to Node 8.0.0 as a workaround, and have been using that since.

**Comment by robsdedude** [comment]
I can now confirm this issue. It's caused by dependencies that have outdated dependencies. So resolving it would mean to switch dependencies which in turn would require code rewrites and I currently have no time to do so. So for the time being I added a note to the README that mentions incompatibility with Node 10 and 12 (28d583d24ea5d03da2f07464f9b91f321afb0379)

**Comment by robsdedude** [comment]
With #76 this should work now for node version 12 as well.
