### ISSUE TITLE
Monpad

### ISSUE THREAD

**Issue by georgefst** [jehervy/node-virtual-gamepads#82]
(This isn't an actual issue, so feel free to close it immediately)

Hi there. I've been working on [a project](https://github.com/georgefst/monpad) with fairly similar goals for the past few months. Indeed I'm quite surprised I didn't come across yours when I was first looking to see if anything similar already existed.

Anyway, I'm just interested in comparing notes:
- Do you just generate evdev events, and what sort of compatibility with games does that get you? I've found that to be recognised by most of the games I care about, I've needed to additionally wrap each device with Xboxdrv to simulate an Xbox controller, which is not a solution I'm particularly happy with.
- Is the requirement to run as root just for `/dev/uinput` and port 80 permissions?
- Is the 4-player limit down to the number of indicator lights on the gamepad image, or is there something more fundamental?
- Are you intending to ever add Windows support? I noticed #80, and have been thinking of using ViGEm myself, but I've been holding back since I don't know much about Windows, and don't have a PC to test it on.

**Comment by robsdedude** [comment]
* So far I haven't tried to use the virtual game-pads with any particular games. I only know that my OS recognizes the virtual gamepads like any other controllers. What games would do with that, no idea. We register as input device and send events to uinput. https://github.com/jehervy/node-virtual-gamepads/blob/master/app/virtual_gamepad.coffee#L40
  * Yes. Theoretically this project would run without root if you adjust the permissions for `/dev/uinput` and change the port. I planed on adding a note about that in the readme. Didn't have the time yet.
  * That limit is obsolete. It was a purely coded limitation because of the LED indicators. Default is 10 now and you can [configure](https://github.com/jehervy/node-virtual-gamepads/blob/develop/config.json#L6) it to what ever you want. The LED indicators might become unintuitive then…
  * Biggest problem with Win support is that I barely could maintain it. I have no easy access to a Windows machine and find it already enough work to maintain this project for Linux only. So basically I'm in a similar position as you.

**Comment by georgefst** [comment]
Thanks!

On the first point, about `uinput`, it certainly *looks* like we're doing essentially the same thing. I'll have to install this tool and check whether we have the same issues.
